# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c624a057ebbb03ea61c3a3408f8793b96bd84662a71bbb5609aa61aef1a570bdc404b6e7425ac09c7742d5379e7eeff57aed22924416085e701936f8ac7a3c7

test:
  secret_key_base: 81ec29c2e1a3dec9592dcbddca569b99fdde589d65a10be88c0d6f1c33facc35e28ee0c153e3a52c3815c6a5a5a0b8917896932ced4a844ec31e729c851dda2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
